#!/usr/bin/env python3
"""Generate the proof stats from the tracking databases.

This is the only place statistics in this repo are allowed to come from.
It reads the databases read-only, renders the stats block, runs hard
assertions, and only then writes:

  - proof/proof-data.json           (machine-readable export)
  - proof/README.md                 (only the block between the STATS markers)

If any assertion fails, nothing is written and the exit code is nonzero.
See VERIFYING.md for the provenance rule this enforces.

Usage:
  python3 proof/generate_proof.py [--with-logpose]
"""

import argparse
import datetime as dt
import json
import os
import re
import sqlite3
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REDDIT_DB = os.path.expanduser("~/clearbox-reddit/data/clearbox-reddit.db")
LOGPOSE_DB = os.path.expanduser("~/logpose/data/logpose.db")
DENYLIST = os.path.expanduser("~/.clearbox/never-publish.txt")

BEGIN = "<!-- STATS:BEGIN (generated by proof/generate_proof.py — do not edit by hand) -->"
END = "<!-- STATS:END -->"

# The public claim string. If real views cross the next million, the language
# rule in VERIFYING.md must be updated FIRST — the assertion below enforces it.
VIEWS_CLAIM = "1.5M+"
VIEWS_FLOOR = 1_500_000
VIEWS_CEIL = 2_000_000
STALE_DAYS = 14

ERA_LABELS = {"karma-building": "Karma-building", "clearbox": "Working era"}
ERA_PROVES = {
    "karma-building": "A real account, posting on real interests, ramps fast — and never got banned doing it",
    "clearbox": "The same account then carries a professional presence: slower, steadier, compounding",
}


def ro(path):
    if not os.path.exists(path):
        sys.exit(f"FAIL: database not found: {path}")
    return sqlite3.connect(f"file:{path}?mode=ro", uri=True)


def gather_reddit():
    con = ro(REDDIT_DB)
    cur = con.cursor()
    cur.execute(
        "SELECT date, link_karma, comment_karma, total_posts, total_comments,"
        " total_views FROM account_snapshots ORDER BY date DESC LIMIT 1"
    )
    row = cur.fetchone()
    if row is None:
        sys.exit("FAIL: no account_snapshots rows")
    as_of, link_k, comment_k, posts, comments, views = row

    eras = []
    for era, items, era_views, days in cur.execute(
        "SELECT era, COUNT(*), SUM(COALESCE(view_count,0)),"
        " ROUND((MAX(created_utc)-MIN(created_utc))/86400.0,1)"
        " FROM items WHERE deleted=0 GROUP BY era ORDER BY MIN(created_utc)"
    ):
        eras.append({
            "era": ERA_LABELS.get(era, era),
            "items": items,
            "views": era_views,
            "days": days,
            "proves": ERA_PROVES.get(era, ""),
        })

    (subreddits,) = cur.execute(
        "SELECT COUNT(DISTINCT subreddit) FROM items WHERE deleted=0"
    ).fetchone()
    (wins,) = cur.execute("SELECT COUNT(*) FROM wins").fetchone()
    leads = dict(cur.execute("SELECT status, COUNT(*) FROM leads GROUP BY status"))
    inbound_replies, replied_items = cur.execute(
        "SELECT COUNT(*), COUNT(DISTINCT item_id) FROM replies"
    ).fetchone()
    (first_day,) = cur.execute(
        "SELECT date(MIN(created_utc),'unixepoch') FROM items"
    ).fetchone()
    con.close()

    span_days = (dt.date.fromisoformat(as_of) - dt.date.fromisoformat(first_day)).days
    months = round(span_days / 30.44, 1)

    return {
        "asOf": as_of,
        "viewsClaim": VIEWS_CLAIM,
        "views": views,
        "karma": {"post": link_k, "comment": comment_k, "total": link_k + comment_k},
        "posts": posts,
        "comments": comments,
        "subreddits": subreddits,
        "wins": wins,
        "leadFunnel": leads,
        "inbound": {"replies": inbound_replies, "itemsWithReplies": replied_items},
        "monthsTracked": months,
        "eras": eras,
    }


def gather_logpose():
    con = ro(LOGPOSE_DB)
    cur = con.cursor()
    signups = dict(cur.execute(
        "SELECT COALESCE(first_touch_channel,'unknown'), COUNT(*)"
        " FROM journeys WHERE signup_at IS NOT NULL"
        " GROUP BY 1 ORDER BY 2 DESC"
    ))
    deals = dict(cur.execute("SELECT stage, COUNT(*) FROM deals GROUP BY stage"))
    con.close()
    return {"signupsByFirstTouchChannel": signups, "dealStages": deals}


def render(stats):
    s = stats
    lines = [
        BEGIN,
        "",
        f"## One account, tracked from zero (as of {s['asOf']})",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Tracked post views | **{s['views']:,}** (the public claim stays **{s['viewsClaim']}**) |",
        f"| Total karma | {s['karma']['total']:,} ({s['karma']['post']:,} post / {s['karma']['comment']:,} comment) |",
        f"| Posts | {s['posts']} |",
        f"| Comments | {s['comments']} |",
        f"| Subreddits reached | {s['subreddits']} |",
        f"| Tracked wins (leads, signups, citations) | {s['wins']} |",
        f"| Inbound engagement | {s['inbound']['replies']} replies received across {s['inbound']['itemsWithReplies']} tracked items |",
        f"| Time span | {s['monthsTracked']} months |",
        "",
        "Two eras, deliberately run in sequence:",
        "",
        "| Era | Items | Views | Days | What it proves |",
        "|---|---|---|---|---|",
    ]
    for e in s["eras"]:
        lines.append(
            f"| {e['era']} | {e['items']} | {e['views']:,} | {e['days']:g} | {e['proves']} |"
        )
    funnel = ", ".join(f"{v} {k}" for k, v in sorted(s["leadFunnel"].items()))
    lines += [
        "",
        f"Lead funnel (self-disclosed only, see the disclosure gate below): {funnel}.",
    ]

    if "logpose" in s:
        lp = s["logpose"]
        lines += [
            "",
            "## Where signups actually came from",
            "",
            "First-touch channel of every tracked signup, from the founder-CRM journey table"
            " (channels and counts only — never names). First-touch attribution undercounts"
            " community channels: a reader who finds a Reddit thread and signs up later from"
            " the site records as web or referral.",
            "",
            "| First-touch channel | Signups |",
            "|---|---|",
        ]
        for ch, n in lp["signupsByFirstTouchChannel"].items():
            lines.append(f"| {ch} | {n} |")
        stages = ", ".join(f"{v} {k}" for k, v in sorted(lp["dealStages"].items()))
        lines += ["", f"Deal pipeline (aggregate counts only): {stages}.", ""]
    else:
        lines.append("")

    lines.append(END)
    return "\n".join(lines)


def assert_safe(block, stats):
    today = dt.date.today()
    as_of = dt.date.fromisoformat(stats["asOf"])
    age = (today - as_of).days
    if age > STALE_DAYS:
        sys.exit(f"FAIL: asOf {stats['asOf']} is {age} days old (> {STALE_DAYS}) — refresh the snapshot first")

    views = stats["views"]
    if not (VIEWS_FLOOR <= views < VIEWS_CEIL):
        sys.exit(
            f"FAIL: views {views:,} outside [{VIEWS_FLOOR:,}, {VIEWS_CEIL:,}) — "
            "update the language rule in VERIFYING.md first, then this script's claim constants"
        )

    if re.search(r"\bu/[A-Za-z0-9_\-]+", block):
        sys.exit("FAIL: a u/ username leaked into the output")

    if os.path.exists(DENYLIST):
        with open(DENYLIST) as f:
            for line in f:
                term = line.strip()
                if not term or term.startswith("#"):
                    continue
                if re.search(term, block, re.IGNORECASE):
                    sys.exit(f"FAIL: denylist term matched in output: {term}")
    else:
        print(f"warning: denylist not found at {DENYLIST}; term scan skipped (release gate requires it)", file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--with-logpose", action="store_true", help="include founder-CRM aggregates")
    args = ap.parse_args()

    stats = gather_reddit()
    if args.with_logpose:
        stats["logpose"] = gather_logpose()

    block = render(stats)
    assert_safe(block, stats)

    readme_path = os.path.join(REPO, "proof", "README.md")
    with open(readme_path) as f:
        readme = f.read()
    if BEGIN not in readme or END not in readme:
        sys.exit(f"FAIL: STATS markers not found in {readme_path}")
    pre = readme.split(BEGIN)[0]
    post = readme.split(END)[1]
    new_readme = pre + block + post
    assert_safe(new_readme, stats)

    json_path = os.path.join(REPO, "proof", "proof-data.json")
    with open(json_path, "w") as f:
        json.dump(stats, f, indent=2, sort_keys=True)
        f.write("\n")
    with open(readme_path, "w") as f:
        f.write(new_readme)
    print(f"wrote {json_path}")
    print(f"wrote stats block in {readme_path} (asOf {stats['asOf']}, views claim {stats['viewsClaim']})")


if __name__ == "__main__":
    main()
